name: workflow-test

on:
  workflow_dispatch:
    secrets:
      MYSECRET:
        required: true

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - run: echo $MYSECRET > testfile.secret && cat testfile.secret && rm -f testfile.secret
        env:
          MYSECRET: ${{ secrets.MYSECRET }}

