name: workflow-test

on:
  workflow_dispatch:
    inputs:
      MYSECRET:
        required: true

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - run: |
          MYSECRET=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.MYSECRET' )
          echo "and the winner is $MYSECRET" > testfile.secret
          cat testfile.secret
          rm -f testfile.secret
          echo $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH
