name: workflow-test

on:
  workflow_dispatch:
    inputs:
      MYSECRET:
        required: true

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "and the winner is $MYSECRET" > testfile.secret && cat testfile.secret && rm -f testfile.secret
        env:
          MYSECRET: ${{ secrets[github.event.inputs.mysecret] }}

